### ISSUE TITLE
expanding the window isn't working properly 

### ISSUE THREAD

**Issue by rjpbroos** [ifilot/mkmcxx-na#1]
When expanding the window to fullscreen mode, there is a mismatch  with the content coupling, leading to a false signalen of the position of the mouse and the underlying content

**Comment by ifilot** [comment]
Mouse pointing is now fixed by transforming screen coordinates to world coordinates using the inverse of the product of the projection **and** view matrix of the Camera object.

For example:
```
const glm::mat4 projection = this->camera->get_projection() * this->camera->get_view();
const glm::mat4 inv = glm::inverse(projection);
const glm::vec4 wp = inv * glm::vec4(xh, yh, 0.0f, 1.0f);
```
